### ISSUE TITLE
Add some papers!

### ISSUE THREAD

**Issue by wangyePHD** [wangkai930418/awesome-diffusion-categorized#11]
Concept learning papers from today arxiv:

1. CustomText: Customized Textual Image Generation using Diffusion Models
2. Personalized Residuals for Concept-Driven Text-to-Image Generation
3. DisenStudio: Customized Multi-subject Text-to-Video Generation with Disentangled Spatial Control

**Comment by wangkai930418** [comment]
Thanks a lot! Already done.
