### ISSUE TITLE
Some latest paper from arxiv today

### ISSUE THREAD

**Issue by wangyePHD** [wangkai930418/awesome-diffusion-categorized#12]
Concept learning：

1. [FreeCustom: Tuning-Free Customized Image Generation for Multi-Concept Composition](https://papers.cool/arxiv/2405.13870)

Image Editing：

1. [EditWorld: Simulating World Dynamics for Instruction-Following Image Editing](https://papers.cool/arxiv/2405.14785)
2. [InstaDrag: Lightning Fast and Accurate Drag-based Image Editing Emerging from Videos](https://papers.cool/arxiv/2405.13722)

Diffusion accelerate：

1. [Improved Distribution Matching Distillation for Fast Image Synthesis](https://papers.cool/arxiv/2405.14867)

Video Diffusion：

1. [Video Diffusion Models are Training-free Motion Interpreter and Controller](https://papers.cool/arxiv/2405.14864)
2. [PoseCrafter: One-Shot Personalized Video Synthesis Following Flexible Poses](https://papers.cool/arxiv/2405.14582)
3. [Text Prompting for Multi-Concept Video Customization by Autoregressive Generation](https://papers.cool/arxiv/2405.13951)
4. [ReVideo: Remake a Video with Motion and Content Control](https://papers.cool/arxiv/2405.13865)
5. [CamViG: Camera Aware Image-to-Video Generation with Multimodal Transformers](https://papers.cool/arxiv/2405.13195)
6. [MotionCraft: Physics-based Zero-Shot Video Generation](https://papers.cool/arxiv/2405.13557)

3D：

1. [Direct3D: Scalable Image-to-3D Generation via 3D Latent Diffusion Transformer](https://papers.cool/arxiv/2405.14832)
2. [MagicDrive3D: Controllable 3D Generation for Any-View Rendering in Street Scenes](https://papers.cool/arxiv/2405.14475)

others：

1. [Good Seed Makes a Good Crop: Discovering Secret Seeds in Text-to-Image Diffusion Models](https://papers.cool/arxiv/2405.14828)

**Comment by wangyePHD** [comment]
I am thrilled to contribute to this outstanding repository. As a PhD student currently pursuing my studies at Jilin University, it is my privilege to share the latest academic papers with you all.

Thank you for creating such a valuable resource. I am excited to be a part of this community.

Warm regards,
Ye Wang

**Comment by wangkai930418** [comment]
Can you send a personal email to me? My email is in my github profile.

**Comment by wangyePHD** [comment]
I have sent a personal email to you, please check it.
