### ISSUE TITLE
Some latest papers from arxiv today！

### ISSUE THREAD

**Issue by wangyePHD** [wangkai930418/awesome-diffusion-categorized#13]
Image Editing

- [FastDrag: Manipulate Anything in One Step](https://papers.cool/arxiv/2405.15769)
- [Enhancing Text-to-Image Editing via Hybrid Mask-Informed Fusion](https://papers.cool/arxiv/2405.15313)

Image Generation

- [Towards Understanding the Working Mechanism of Text-to-Image Diffusion Model](https://papers.cool/arxiv/2405.15330)
- [SG-Adapter: Enhancing Text-to-Image Generation with Scene Graph Guidance](https://papers.cool/arxiv/2405.15321)

Video

- [NVS-Solver: Video Diffusion Model as Zero-Shot Novel View Synthesizer](https://papers.cool/arxiv/2405.15364)

Style 

- [StyleMaster: Towards Flexible Stylized Image Generation with Diffusion Models](https://papers.cool/arxiv/2405.15287)

**Comment by FaceAdapter** [comment]
And I would like to kindly request that you include our latest paper, code, and Gradio in the project. We recently made them open source just a few days ago and would be thrilled to have them included.

**Comment by FaceAdapter** [comment]
.I would like to kindly request that you include our latest paper, code, and Gradio in the project. We recently made them open source just a few days ago and would be thrilled to have them included:

New Concept Learning
---
Face Adapter for Pre-Trained Diffusion Models with Fine-Grained ID and Attribute Control
https://github.com/FaceAdapter/Face-Adapter
https://arxiv.org/pdf/2405.12970
