### ISSUE TITLE
Update information about TI2V-Zero 

### ISSUE THREAD

**Issue by nihaomiao** [wangkai930418/awesome-diffusion-categorized#15]
Hi, @wangkai930418,

thanks a lot for your impressive work!

Our TI2V-Zero has been accepted to CVPR 2024, and our code is also available at this [link](https://github.com/merlresearch/TI2V-Zero). Could you update the information on our paper?

Thanks again for your time!

**Comment by wangkai930418** [comment]
Thanks for your update! I just did it.
