### ISSUE TITLE
paper update

### ISSUE THREAD

**Issue by YasminZhang** [wangkai930418/awesome-diffusion-categorized#19]
Can you help me update the following paper's info? Thanks in advance. 

Object-Conditioned Energy-Based Attention Map Alignment in Text-to-Image Diffusion Models
[[ECCV 2024](https://arxiv.org/abs/2404.07389)] [[Code](https://github.com/YasminZhang/EBAMA/tree/master)]

**Comment by wangkai930418** [comment]
Done!
