### ISSUE TITLE
Add a paper

### ISSUE THREAD

**Issue by EvaFlower** [wangkai930418/awesome-diffusion-categorized#22]
Hi,

Thanks for maintaining this great repo. Could you help add our recent work?

PROUD: PaRetO-gUided diffusion model for multi-objective generation
[ECML2024 Machine Learning Journal Track](https://link.springer.com/article/10.1007/s10994-024-06575-2), [Code](https://github.com/EvaFlower/Pareto-guided-diffusion-model)

**Comment by wangkai930418** [comment]
Done!
