### ISSUE TITLE
Add papers of post-training

### ISSUE THREAD

**Issue by Bili-Sakura** [wangkai930418/awesome-diffusion-categorized#23]
Wallace, B., Dang, M., Rafailov, R., Zhou, L., Lou, A., Purushwalkam, S., Ermon, S., Xiong, C., Joty, S., & Naik, N. (2024). Diffusion Model Alignment Using Direct Preference Optimization. 8228–8238. https://openaccess.thecvf.com/content/CVPR2024/html/Wallace_Diffusion_Model_Alignment_Using_Direct_Preference_Optimization_CVPR_2024_paper.html

Black, K., Janner, M., Du, Y., Kostrikov, I., & Levine, S. (2023, October 13). Training Diffusion Models with Reinforcement Learning. The Twelfth International Conference on Learning Representations. https://openreview.net/forum?id=YCWjhGrJFD

Fan, Y., Watkins, O., Du, Y., Liu, H., Ryu, M., Boutilier, C., Abbeel, P., Ghavamzadeh, M., Lee, K., & Lee, K. (2023). DPOK: Reinforcement Learning for Fine-tuning Text-to-Image Diffusion Models. Advances in Neural Information Processing Systems, 36, 79858–79885. https://proceedings.neurips.cc/paper_files/paper/2023/hash/fc65fab891d83433bd3c8d966edde311-Abstract-Conference.html

**Comment by wangkai930418** [comment]
Thanks! Done it yet.
