### ISSUE TITLE
Add a paper: TrailBlazer

### ISSUE THREAD

**Issue by choasma** [wangkai930418/awesome-diffusion-categorized#8]
Hello! Thank you for your hard working for this awesome repo. We would be honored to have our paper included in this listing. Thank you.

TrailBlazer: Trajectory Control for Diffusion-Based Video Generation
https://hohonu-vicml.github.io/Trailblazer.Page/

**Comment by wangkai930418** [comment]
Done!

**Comment by choasma** [comment]
Thank you! Really appreciated your time. (L)
