### ISSUE TITLE
CVPR2023-Image Translation

### ISSUE THREAD

**Issue by ISCANCHU** [wangkai930418/awesome-diffusion-categorized#9]
Hello,

Can you kindly add our work on image translation with Brownian Bridge Diffusion Models published in CVPR23? We have released the code on Github.

Its information is as follows:

BBDM: Image-to-image Translation with Brownian Bridge Diffusion Models, Bo Li, Kaitao Xue, Bin Liu, Yu-Kun Lai, 2023 IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR), Vancouver, BC, Canada, 2023, pp. 1952-1961
Code: https://github.com/xuekt98/BBDM

Best regards
Bo

**Comment by wangkai930418** [comment]
Done!
